# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cookr-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cookr-iOS
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'MessageInputBar'

  target 'cookr-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cookr-iOSUITests' do
    # Pods for testing
  end

end
